name: OpenSSL compatibility

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  build:

    runs-on: ubuntu:22.04

    steps:
    - name: Install dependencies (OpenSSL-3.0.2)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libevent-dev \
            libssl-dev \
            libpq-dev libmariadb-dev libsqlite3-dev \
            libhiredis-dev \
            libmongoc-dev \
            libmicrohttpd-dev
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: apps tests
      run: cd examples && ./run_tests.sh


  build:

    runs-on: ubuntu:20.04 (OpenSSL-1.1.1)

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libevent-dev \
            libssl-dev \
            libpq-dev libmariadb-dev libsqlite3-dev \
            libhiredis-dev \
            libmongoc-dev \
            libmicrohttpd-dev
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: apps tests
      run: cd examples && ./run_tests.sh

  build:

    runs-on: ubuntu:16.04 (OpenSSL-1.0.2)

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libevent-dev \
            libssl-dev \
            libpq-dev libmariadb-dev libsqlite3-dev \
            libhiredis-dev \
            libmongoc-dev \
            libmicrohttpd-dev
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: apps tests
      run: cd examples && ./run_tests.sh
